pipeline testing

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,14 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
+# Run linting and formatting checks
 npx lint-staged
+
+## Run Snyk test
+#snyk test
+#
+## Check the exit status of the previous command
+#if  [ $? -ne 0 ]; then
+#  echo "Errors or vulnerabilities were found. Please fix them before committing."
+#  exit 1
+#fi
